spring.application.name=api-gateway

server.port=8080



jwt.secret=MySecretKeyMySecretKeyMySecretKey12345

spring.cloud.gateway.discovery.locator.enabled=true

spring.cloud.gateway.discovery.locator.lower-case-service-id=true
